# Generated by Django 2.2 on 2021-07-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='user_wish',
            new_name='wished_by',
        ),
        migrations.AddField(
            model_name='wish',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_wishes', to='main.User'),
        ),
    ]
