# Generated by Django 2.2 on 2021-07-20 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210720_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='wish_granted',
            fields=[
                ('wish_grant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.Wish')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grant_to', models.ManyToManyField(related_name='wish_granted', to='main.User')),
            ],
        ),
    ]
