# Generated by Django 2.2 on 2021-07-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210720_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='wish_granted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.DeleteModel(
            name='wish_granted',
        ),
    ]
