# Generated by Django 2.2 on 2021-07-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210721_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='wish',
            name='liked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
