# Generated by Django 2.2 on 2021-07-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210721_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='liked',
        ),
        migrations.AddField(
            model_name='wish',
            name='users_who_liked',
            field=models.ManyToManyField(related_name='liked_wishes', to='main.User'),
        ),
    ]
